name: Distribute

on:
  push:
    branches: [ main ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute
